services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: loop-closer-backend
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data
      - ./server/users_db.json:/app/server/users_db.json
      - ./users_db.json:/app/users_db.json
      - ./mock_db.json:/app/mock_db.json
      - ./execution/analyzed_posts.json:/app/execution/analyzed_posts.json
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/execution
      - FRONTEND_URL=https://theloopcloser.com
      - PESAPAL_CALLBACK_URL=https://api.theloopcloser.com/api/payment/callback
    restart: always

  app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: loop-closer-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.theloopcloser.com
    restart: always
    volumes:
      - ./client/waitlist.csv:/app/waitlist.csv

volumes:
  data:
